name: SwiftUIKitDemo
options:
  bundleIdPrefix: com.example
packages:
  SwiftUIKit:
    path: ../
targets:
  SwiftUIKitDemo-iOS:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: '17.0'
    sources: [Sources]
    resources: [Resources]
    dependencies:
      - package: SwiftUIKit
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SwiftUIKitDemo
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchScreen: {}
  SwiftUIKitDemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [../Tests/SwiftUIKitDemoUITests]
    dependencies:
      - target: SwiftUIKitDemo-iOS
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ../Tests/SwiftUIKitDemoUITests/Info.plist

workspace:
  name: SwiftUIKitDemo
  projects:
    - SwiftUIKitDemo.xcodeproj 