name: SwiftUIKitDemo
options:
  bundleIdPrefix: com.example
packages:
  SwiftUIKit:
    path: ../
targets:
  SwiftUIKitDemo:
    type: application
    platform: [iOS, macOS, tvOS, watchOS, visionOS]
    deploymentTarget:
      iOS: '17.0'
      macOS: '14.0'
      tvOS: '17.0'
      watchOS: '10.0'
      visionOS: '1.0'
    sources: [Sources]
    resources: [Resources]
    dependencies:
      - package: SwiftUIKit
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SwiftUIKitDemo
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchScreen: {} 