# .cursor-project.yml
mode: project
agent:
  autoRun: true
  autoPush: true
  autoCommit: true
  autoFormat: true
  autoLint: true
  promptOnDestructive: false
  force: false
  logLevel: debug
  logFile: /tmp/cursor-agent-swiftuikit.log
  notificationLevel: errors
  environment:
    SWIFTUIKIT_SCHEME: "SwiftUIKitDemo_iOS"
    SWIFTUIKIT_WORKSPACE: "swift-uikit/DemoApp/SwiftUIKitDemo.xcodeproj/project.xcworkspace"
workflows:
  build: _scripts/swiftuikit_dev_workflow.sh build-ios
  test: _scripts/swiftuikit_dev_workflow.sh test
  clean: _scripts/swiftuikit_dev_workflow.sh clean
  monitor: _scripts/swiftuikit_dev_workflow.sh monitor
  fullCycle: _scripts/swiftuikit_dev_workflow.sh full-cycle
  status: _scripts/swiftuikit_dev_workflow.sh status 